# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Infrastructure
  jobs:
  - job: 
    displayName: Preview/Deploy Infrastrucutre
    steps:    
    - task: Pulumi@1
      displayName: Preview Infrastructure
      inputs:
        azureSubscription: 'Pay-As-You-Go(3bd10068-0c35-4ed1-8436-1b052ac96a2b)'
        command: 'preview'
        cwd: "infra/"
        stack: 'two4suited/flyballstats.com/dev'
      env:
        PULUMI_ACCESS_TOKEN: $(pulumi_access_token)
    - task: Pulumi@1
      displayName: Deploy Infrastructure
      inputs:
        azureSubscription: 'Pay-As-You-Go(3bd10068-0c35-4ed1-8436-1b052ac96a2b)'
        command: 'up'
        args: '--skip-preview'
        cwd: 'infra/'
        stack: 'two4suited/flyballstats.com/dev'
      env:
        PULUMI_ACCESS_TOKEN: $(pulumi_access_token)
- stage: Deploy_Code
  jobs:
  - job:
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
