# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Infrastructure
  jobs:
  - job: 
    displayName: Deploy Infrastrucutre
    steps:    
    - task: Pulumi@1
      inputs:
        azureSubscription: 'Pay-As-You-Go(3bd10068-0c35-4ed1-8436-1b052ac96a2b)'
        command: 'preview'
        cwd: "infra/"
        stack: 'flyballstats.com'
