name: "CI: Build & Test"

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    name: Restore, Build, Test (net9)
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      DOTNET_NOLOGO: 'true'
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
      SOLUTION_PATH: src/flyballstats.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}-${{ hashFiles('**/global.json') }}-${{ hashFiles('**/nuget.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore "$SOLUTION_PATH"

      - name: Build
        run: dotnet build "$SOLUTION_PATH" --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test "$SOLUTION_PATH" \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=test-results.trx" \
            --logger "console;verbosity=detailed"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
          if-no-files-found: ignore

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Tests
          path: "**/TestResults/*.trx"
          reporter: dotnet-trx
          fail-on-error: false
          fail-on-empty: false
